[package]
name = "semantic-release-cargo"
version ="1.0.2"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>", "Eric Crosson <eric.s.crosson@utexas.edu>"]
edition = "2018"
description = "A CLI to integrate Rust into a semantic-release workflow."
readme = "README.md"
repository = "https://github.com/semantic-release-cargo/semantic-release-cargo"
license = "MIT OR Apache-2.0"
keywords = ["release", "semantic-release", "command-line-tool"]
categories = ["command-line-utilities", "development-tools::build-utils"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.38"
guppy = "0.15.1"
human-panic = "1.0.3"
itertools = "0.10.0"
log = "0.4.14"
loggerv = "0.7.2"
napi = { version = "2", features = ["error_anyhow"]}
napi-derive = "2.9.3"
serde_json = "1.0.62"
serde = { version = "1.0.123", features = ["derive"] }
structopt = "0.3.21"
thiserror = "1.0.23"
toml_edit = "0.2.0"
url = { version = "2.2.0", features = ["serde"] }

[build-dependencies]
napi-build = "2"

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "3.2.0"
fs_extra = "1.2.0"
semver = "1.0"
