[package]
name = "semantic-release-rust"
version = "0.1.0"
authors = ["Steven Bosnick <sbosnick@sympatico.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
human-panic = "1.0.3"
log = "0.4.8"
loggerv = "0.7.2"
structopt = "0.3.15"
anyhow = "1.0.31"
thiserror = "1.0.20"
guppy = "0.5.0"
itertools = "0.9.0"
toml_edit = "0.2.0"

[dev-dependencies]
assert_matches = "1.3.0"
tempfile = "3.1.0"
fs_extra = "1.1.0"
semver = "0.9.0"
